name: Mon Workflow

on:
  push:
    branches: [develop]

jobs:
  lint:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint files
        run: find . -name "*.php" -print0 | xargs -0 -n1 php -l *.php
